_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.11
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 2
                - 13
                - 16
                - 23
                - 34
                - 35
                - 55
            "4": 3.11.11
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
env:
    value:
        T_T: |-
            [[[ 0.          0.        ]
              [ 6.          5.4       ]
              [ 4.          1.4       ]
              ...
              [20.          8.32586332]
              [17.          7.76659514]
              [15.          9.33809402]]

             [[ 6.          5.4       ]
              [ 0.          0.        ]
              [10.          5.57853027]
              ...
              [21.          7.85875308]
              [23.          8.49705831]
              [21.          9.95389371]]

             [[ 4.          1.4       ]
              [10.          5.57853027]
              [ 0.          0.        ]
              ...
              [16.          7.07106781]
              [13.          6.40312424]
              [11.          7.96241169]]

             ...

             [[20.          8.32586332]
              [21.          7.85875308]
              [16.          7.07106781]
              ...
              [ 0.          0.        ]
              [ 4.          1.8       ]
              [ 5.          2.40831892]]

             [[17.          7.76659514]
              [23.          8.49705831]
              [13.          6.40312424]
              ...
              [ 4.          1.8       ]
              [ 0.          0.        ]
              [ 2.          1.6       ]]

             [[15.          9.33809402]
              [21.          9.95389371]
              [11.          7.96241169]
              ...
              [ 5.          2.40831892]
              [ 2.          1.6       ]
              [ 0.          0.        ]]]
        courier_init:
            - -1
            - 40
        drone_speed: 0.5
        etas:
            - 1
            - 2
        len_q: 2
        max_exp: 2
        max_lat: 70
        max_q: 2000
        max_tau: 30
        max_utility: 35
        modalities:
            - car
            - drone
        n_links: 76
        n_nodes: 24
        name: drone_1
        net: SiouxFalls
        num_couriers:
            - 15
            - 10
        rate: 2
        rates_d:
            - 0.05
            - 0.05
            - 0.05
            - 0.05
            - 0.05
            - 0.05
            - 0.05
            - 0.05
            - 0.01
            - 0.01
            - 0.01
            - 0.05
            - 0.05
            - 0.05
            - 0.05
            - 0.01
            - 0.01
            - 0.05
            - 0.05
            - 0.05
            - 0.05
            - 0.05
            - 0.05
            - 0.05
        rates_p:
            - 0
            - 0
            - 0
            - 0
            - 0
            - 0
            - 0
            - 0
            - 0.2
            - 0.2
            - 0.2
            - 0
            - 0
            - 0
            - 0
            - 0.2
            - 0.2
            - 0
            - 0
            - 0
            - 0
            - 0
            - 0
            - 0
        vot_means:
            - 0.8
            - 0.8
            - 0.8
            - 1.2
            - 1.2
            - 0.8
            - 0.8
            - 1.2
            - 5
            - 5
            - 5
            - 0.8
            - 0.8
            - 1.2
            - 1.2
            - 5
            - 5
            - 1.2
            - 1.2
            - 0.8
            - 0.8
            - 1.2
            - 1.2
            - 0.8
        vot_stds:
            - 0.01
            - 0.01
            - 0.01
            - 0.01
            - 0.01
            - 0.01
            - 0.01
            - 0.01
            - 0.01
            - 0.01
            - 0.01
            - 0.01
            - 0.01
            - 0.01
            - 0.01
            - 0.01
            - 0.01
            - 0.01
            - 0.01
            - 0.01
            - 0.01
            - 0.01
            - 0.01
            - 0.01
