# meta-parameters
project_name : ''
run_name : ''
seed: ''
device: 'cpu'

model:
  name: 'DDPG'
  net_arch: [128, 128]
  policy: "MultiInputPolicy"
  learning_rate: 1e-3               # Stable learning rate for DDPG
  buffer_size: 1000000               # Replay buffer size
  batch_size: 256                    # Minibatch size
  learning_starts: 100             # Steps before training starts
  tau: 0.005                         # Target smoothing coefficient
  gamma: 0.99                        # Discount factor
  action_noise: null                 # Define in code if needed
  train_freq: 1                      # Update frequency
  gradient_steps: 1                  # Number of gradient steps per update
  tensorboard_log: "DDPG"
  verbose: 2

env_setup:
  num_proc: 1
  timelimit: 200

algo:
  name: "default"
  total_timesteps: 5000000
  log_interval: 1
